# Generated by Django 4.2.5 on 2023-09-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('km_runs', models.PositiveIntegerField()),
            ],
        ),
    ]
