# Generated by Django 4.2.5 on 2023-09-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=200)),
                ('vehicle_model', models.CharField(max_length=200, null=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('km_runs', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Olx',
        ),
    ]
