# Generated by Django 4.2.5 on 2023-09-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_vehicles_delete_olx'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
